---
roles:
  - name: stackhpc.os-flavors
  - name: stackhpc.os-images
  - name: stackhpc.os-networks
  - name: stackhpc.os-projects
  - name: stackhpc.os_host_aggregates
  - name: stackhpc.os-container-clusters

collections:
  - name: openstack.cloud
