---
- name: Ensure {{cookiecutter.cloud_longname}} OpenStack nova host aggregates exist
  hosts: localhost
  tags:
    - host_aggregates
  roles:
    - role: stackhpc.os_host_aggregates
      os_host_aggregates_venv: "{{ '{{' }} {{cookiecutter.cloud_shortname}}_venv }}"
      os_host_aggregates_auth_type: "{{ '{{' }} openstack_auth_type }}"
      os_host_aggregates_auth: "{{ '{{' }} openstack_auth }}"
      os_host_aggregates_cacert: "{{ '{{' }} openstack_cacert }}"
      os_host_aggregates: "{{ '{{' }} {{cookiecutter.cloud_shortname}}_host_aggregates }}"
