---
- name: Generate {{cookiecutter.cloud_longname}} software images
  hosts: localhost
  tags:
    - images
  roles:
    - role: stackhpc.os-images
      os_images_venv: "{{ '{{' }} {{cookiecutter.cloud_shortname}}_venv }}"
      os_images_cache: "{{ '{{' }} ansible_env.PWD }}/{{cookiecutter.cloud_shortname}}-config-image-cache"
      os_images_auth_type: "{{ '{{' }} openstack_auth_type }}"
      os_images_auth: "{{ '{{' }} openstack_auth }}"
      os_images_list: "{{ '{{' }} {{cookiecutter.cloud_shortname}}_images }}"
      os_images_elements: "{{ '{{' }} {{cookiecutter.cloud_shortname}}_image_elements }}"
      os_images_git_elements: "{{ '{{' }} {{cookiecutter.cloud_shortname}}_image_git_elements }}"
